import { defaultLang } from './i18n';
import fs from 'fs';
import path from 'path';

/**
 * Dictionary cache to avoid redundant file reads
 */
const dictionaryCache = new Map<string, Record<string, string>>();

/**
 * Get translated dictionary for a given language
 * Loads pre-compiled translations from /locales directory
 * (Generated by: npm run i18n:extract && npm run i18n:translate)
 */
export async function getDictionary(lang?: string | null): Promise<Record<string, string>> {
  // Normalize language code
  const normalizedLang = (lang ?? defaultLang).toLowerCase();
  
  // Check cache
  if (dictionaryCache.has(normalizedLang)) {
    return dictionaryCache.get(normalizedLang)!;
  }

  try {
    // Try to load language file
    const localesDir = path.join(process.cwd(), 'locales');
    const languageFile = path.join(localesDir, `${normalizedLang}.json`);
    
    if (fs.existsSync(languageFile)) {
      const content = fs.readFileSync(languageFile, 'utf-8');
      const translations = JSON.parse(content);
      dictionaryCache.set(normalizedLang, translations);
      return translations;
    }

    // Fallback to default language
    console.warn(`Translation file not found for ${lang}, using ${defaultLang}`);
    const defaultFile = path.join(localesDir, `${defaultLang}.json`);
    
    if (fs.existsSync(defaultFile)) {
      const content = fs.readFileSync(defaultFile, 'utf-8');
      const translations = JSON.parse(content);
      dictionaryCache.set(normalizedLang, translations);
      return translations;
    }

    // No translations available
    console.warn(`No translation files found. Run: npm run i18n:sync`);
    return {};
  } catch (error) {
    console.error(`Failed to load dictionary for ${lang}:`, error);
    return {};
  }
}

/**
 * Server-side translation helper
 * Uses pre-loaded dictionary
 */
export function t(
  dictionary: Record<string, string>,
  key: string,
  fallback?: string
): string {
  return dictionary[key] || fallback || key;
}

